The intention of this notebook is to do exploratory data analysis (EDA) on the GPU metrics collected.

In [67]:
import pymongo 
from pymongo import MongoClient
import os 
from dotenv import load_dotenv, find_dotenv
import numpy as np
import pandas as pd

In [ ]:
load_dotenv(find_dotenv())
my_password = os.environ.get("RAHUL_PASS")

documents = {}
inital = {}

In [80]:
try: 
    uri = f"mongodb+srv://rr1437:{my_password}@prometrics.h105zsq.mongodb.net/?retryWrites=true&w=majority&appName=ProMetrics"
    client = MongoClient(uri)

    database = client["main"]
    collection = database["hundred_util_baseline"]

    results = collection.find({"Collect" : "True"})

    for index, result in enumerate(results):
        documents[index] = result
        # print(index, result)
        # print(result)

    results = collection.find({"Collect" : "False"})
    intial = results[0]

    client.close()

except Exception as e:
    raise Exception(
        "Recieved the following error:" + e
    )

In [100]:
intial['GPU Clock Limit (GHz)']= intial['GPU Clock Limit (MHz)']/1000
intial['Memory Clock Limit (GHz)']= intial['Memory Clock Limit (MHz)']/1000

In [102]:
documents['GPU Clock Utilization'] = documents['GPU Current Clock (GHz)']/ intial['GPU Clock Limit (GHz)']
documents['Memory Clock Utilization'] = documents['Memory Current Clock (GHz)']/ intial['Memory Clock Limit (GHz)']

C:\Users\rahul\AppData\Local\Temp\ipykernel_1680\3718586011.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  documents['GPU Clock Utilization'] = documents['GPU Current Clock (GHz)']/ intial['GPU Clock Limit (GHz)']
C:\Users\rahul\AppData\Local\Temp\ipykernel_1680\3718586011.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  documents['Memory Clock Utilization'] = documents['Memory Current Clock (GHz)']/ intial['Memory Clock Limit (GHz)']

In [97]:
percent = documents['GPU Current Clock (GHz)']/intial['GPU Clock Limit (MHz)']

In [70]:
documents = pd.DataFrame(documents)
documents = documents.T
documents.drop(columns=['_id'], inplace=True)

In [71]:
documents

,GPU Utilization (%),Power Draw (Watts),GPU Temp (°C),GPU Current Clock (MHz),Memory Current Clock (MHz),Memory Allocation Used (MB),Memory Utilization (%),GPU Stress,Current Time,Time Delta,Status,Iteration,Collect
0,0.0,24.37,24.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:45:38,1,Live,1,True
1,0.0,24.37,24.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:45:40,2,Live,2,True
2,0.0,24.36,24.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:45:41,3,Live,3,True
3,0.0,24.36,24.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:45:43,5,Live,4,True
4,0.0,24.36,24.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:45:44,6,Live,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,0.0,26.02,36.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:50:12,275,Live,209,True
209,0.0,26.02,36.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:50:14,276,Live,210,True
210,0.0,26.02,36.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:50:15,277,Live,211,True
211,0.0,26.02,36.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:50:16,278,Live,212,True
212,0.0,26.02,36.0,135000000.0,877000000.0,5242880.0,0.0,Off,13:50:17,280,Live,213,True

In [72]:
clock_speeds = ['GPU Current Clock (MHz)', 'Memory Current Clock (MHz)', ]
clock_speeds_c = ['GPU Current Clock (GHz)', 'Memory Current Clock (GHz)', ]
for i in clock_speeds:
    documents[i] = documents[i]/1000
    documents.rename(columns={i: clock_speeds_c[clock_speeds.index(i)]}, inplace=True)

In [73]:
documents

,GPU Utilization (%),Power Draw (Watts),GPU Temp (°C),GPU Current Clock (GHz),Memory Current Clock (GHz),Memory Allocation Used (MB),Memory Utilization (%),GPU Stress,Current Time,Time Delta,Status,Iteration,Collect
0,0.0,24.37,24.0,135000.0,877000.0,5242880.0,0.0,Off,13:45:38,1,Live,1,True
1,0.0,24.37,24.0,135000.0,877000.0,5242880.0,0.0,Off,13:45:40,2,Live,2,True
2,0.0,24.36,24.0,135000.0,877000.0,5242880.0,0.0,Off,13:45:41,3,Live,3,True
3,0.0,24.36,24.0,135000.0,877000.0,5242880.0,0.0,Off,13:45:43,5,Live,4,True
4,0.0,24.36,24.0,135000.0,877000.0,5242880.0,0.0,Off,13:45:44,6,Live,5,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,0.0,26.02,36.0,135000.0,877000.0,5242880.0,0.0,Off,13:50:12,275,Live,209,True
209,0.0,26.02,36.0,135000.0,877000.0,5242880.0,0.0,Off,13:50:14,276,Live,210,True
210,0.0,26.02,36.0,135000.0,877000.0,5242880.0,0.0,Off,13:50:15,277,Live,211,True
211,0.0,26.02,36.0,135000.0,877000.0,5242880.0,0.0,Off,13:50:16,278,Live,212,True
212,0.0,26.02,36.0,135000.0,877000.0,5242880.0,0.0,Off,13:50:17,280,Live,213,True

In [74]:
documents.to_csv("../samples/hundred_true.csv")